### ISSUE TITLE
Current DAG structure critical issue

### ISSUE THREAD

**Issue by leahcornelius** [avrio-project/avrio-core#15]
Currently a block is added to both the receiver and sender's blockchain. This works provided the sender and the receiver have exactly the same block height. If they do not then there will be two blocks at certain heights. To solve this a block can be one of two types:
* Send 
* Receive
Send blocks are made by the sender and are put straight into the mempool after being validated. Once they have at least 2/3 signatures from the committee then the block is sent to the committee dealing with the receiver. The receiving committee then forms a receive block with the exact same data as the send block. Unlike send blocks, receiver blocks do not have to be signed by the wallet. The are created by the committee that deals with that chain and to be valid must reference a block that is in the mempool. If a node receives a receive block it first looks in the mempool for the block that the receive block references. If it does not have it then it asks the node it got the receiving block from to sen the corresponding send block. If the send block is valid and all fields of the receive block other than hash, timestamp, height, type or signatures are the same and the node signatures are valid then it accepts both blocks. If a node does not respond with a send block related to the receive block then the node simply ignores the block. 
[POLL] 
Should we add the receive block without a parent (the send block) to the mempool, tell me what you think on this one as i cant decide.

Some edits that need to be done:

-  Never enact a send block, you only enact receive blocks
- Do not save a send block until we see a (valid) receive block, until then add it to the mempool and wait
- Periodically ask peers for a receive block relating to the send block, if after 3 hours we have not got one purge the block from the mempool until we next see it.
- Add the following parameters to block:
 - block_type: Custom enum?
 - send_block_hash: Option<String>
 - anything else?

Im going to make a separate branch and work on this, if anyone want to help out that would be great. Ill be adding code documentation as i go along as well as fixing any warnings

**Comment by leahcornelius** [comment]
Another thing we need to consider is who will generate the receiving blocks in the pre-PON test nets. Im thinking maybe the sender should construct it as we do not need any fullnode signatures yet anyway. The only attack vector i can see with this is the potential for someone to spam loads of really large blocks and never broadcast a receive block for it. It would fill up the mempool and cause some issues ith low ram nodes.

**Comment by leahcornelius** [comment]
Wont be an issue in the mainnet or once we have PON as the fullnodes would be making the receive block, not the sender.

**Comment by leahcornelius** [comment]
Working on this now.

**Comment by leahcornelius** [comment]
Going to rename blocks type, send and receive are clunky as a send block is not always SENDING currency per say. I believe eth had a nice article on something similar will try to find

**Comment by leahcornelius** [comment]
ah yes, credit and receipt. Let me do a vote here

**Comment by leahcornelius** [comment]
Rename send, recieve blocks to Credit, debit blocks (thumbs up for yes)

**Comment by leahcornelius** [comment]
OR:
Rename send, receive blocks to Credit, receipt blocks (thumbs up for yes) 
VOTE ONLY ONE

**Comment by TheDevMinerTV** [comment]
:+1:

**Comment by leahcornelius** [comment]
which one? I think the receipt one is clearer

**Comment by TheDevMinerTV** [comment]
The reciept one makes more sense to me.

**Comment by leahcornelius** [comment]
Cool, will go with that

**Comment by leahcornelius** [comment]
trying to get avrio compiled on my rpi 4 and 3. Then set up an auto recompiler so they auto recompile and run every time i commit to github. Means i can test the syncing code much quicker

**Comment by TheDevMinerTV** [comment]
I think I was already doing that 🤔

**Comment by leahcornelius** [comment]
But apparently there are a huge amount of AES optimisation instruction sets not in arm7, so it takes FOREVER and keeps crashing

**Comment by leahcornelius** [comment]
oh?

**Comment by TheDevMinerTV** [comment]
oh, not for ARM though, only x86_64

**Comment by leahcornelius** [comment]
i see

**Comment by leahcornelius** [comment]
yeh arm doesnt allow deriving integer to vector conversions

**Comment by leahcornelius** [comment]
I believe the fix-the-branch dag has a validation issue. Annoyingly as I accidentally merged it with the p2p refactor branch I haven't yet separated the two as the root cause. From what I remember it was a hash mismatch. Could be from the way receive blocks are validated or constructed. Im looking at it now

**Comment by leahcornelius** [comment]
Believed to be resolved, need to write unit tests to confirm.
